### PR TITLE
OneDrive Business Support and version update

### PR DESCRIPTION
**Pull request by ComictypX**
I added OneDrive Business Support (which needs Duplicacy 2.5.0) and so updated Duplicancy to Version 2.7.2 and the alpine Baseimage to 3.13.

https://github.com/gilbertchen/duplicacy/wiki/Managing-Passwords

### CODE REVIEW

**Comment by christophetd** [comment]
Thanks for your contribution! I updated Duplicacy version to 2.7.2 in ddb483f. Let me take the PR from there and get it merged

**Comment by christophetd** [comment]
@ComictypX Can you tick the option "Allow edits from repo maintainers" on your PR? https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork It will allow me to reuse your commit and rebase on latest master without loosing your name.

**Comment by ComictypX** [comment]
Sure thing, but it is actually already ticked. I unticked and reticked it just to be sure :)

**Comment by christophetd** [comment]
Weird, I can't push to your fork. Do you mind rebasing on latest master?

**Comment by christophetd** [comment]
Wonderful, should be good now! I believe CI is failing because the PR is from a fork, hence not passing the right secret. Thanks for your contribution!

**Pull request merged**
